baseURL = "https://thekitty.zone/"
languageCode = "en-us"
title = "The kitty zone"
# How many feed entries to load at once
paginate = 6

[taxonomies]
tag = "tags"

[author]
name = "11Tuvork28"
image = "images/img.png"
about = "Is this... Is this really real? Where are all the kittens and cats if this is the kitty zone?"

[params]
skin = "macintosh"
mainSections = "posts"
#
# For IndieAuth and the author card
#
githubuser = "11tuvork28"
# twitteruser = "chihiro" # no @ in front
# mastodon = "https://mastodon.technology/@chihiro" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
home = ["HTML", "JSON", "RSS"]